export { TAU, clamp, lerp, easeOutQuint, r2 } from './math'
export {
  PROFILE_SAMPLES,
  circle,
  blend,
  blendSilhouettes,
  toPoints,
  closedPath,
  polarPolygon,
  superellipse,
  profileFromPolygon,
  hullOfCircles,
  radiusAtAngle,
  silhouetteFromRadii,
  eggProfile,
  regularPolygonProfile,
  silhouettePath,
  viewBoxAttr,
  BODY_RADIUS,
  VIEW_SCALE,
  VIEW_CX,
  VIEW_CY,
  VIEW_HALF,
  VIEW_SIZE,
  type Point,
  type Silhouette,
} from './morph'
export {
  ANIMATION_STATES,
  STATE_REGISTRY,
  STATE_SILHOUETTES,
  DEFAULT_MORPH_MS,
  isAnimationState,
  silhouetteFor,
  morphSilhouette,
  morphPath,
  morphProgress,
  pathForState,
  sampleMorph,
  type AnimationState,
  type MorphDot,
  type MorphFrame,
  type StateEntry,
} from './states'
export {
  STATE_SLUGS,
  slugOf,
  stateFromSlug,
  fragmentPour,
  lireHash,
  ecrireHash,
  type StateSlug,
  type HashEtat,
} from './hash'
export {
  EYE_H,
  EYE_SPLIT,
  EYE_W,
  REST_GAZE,
  blinkScale,
  eyePoses,
  resolveGaze,
  type EyePose,
  type GazeInput,
  type HeadGaze,
} from './face'
export {
  SHAPES,
  SHAPE_BY_ID,
  DEFAULT_SHAPE,
  COLORS,
  COLOR_BY_ID,
  DEFAULT_COLOR,
  isShapeId,
  isColorId,
  resolveShape,
  resolveColour,
  type ShapeId,
  type BotShape,
  type ColorId,
  type BotColor,
} from './skins'
export {
  EXPRESSIONS,
  EXPRESSION_BY_ID,
  DEFAULT_EXPRESSION,
  isExpressionId,
  resolveExpression,
  blendExpression,
  type ExpressionId,
  type EyeCfg,
  type BotExpression,
} from './expressions'
export {
  STATE_GEOMETRY,
  poseRadii,
  resolveStateGeometry,
  usesCustomiserShape,
  type FacePolicy,
  type PoseTransform,
  type ResolvedGeometry,
  type StateGeometry,
} from './authority'
export {
  DEFAULT_SIZE,
  DEFAULT_PAPER,
  activeSilhouette,
  sampleAvatar,
  sampleLiveMorph,
  gazeAttr,
  colourIdOf,
  type AvatarSpec,
  type AvatarEye,
  type AvatarFrame,
  type LiveMorphSpec,
} from './avatar'
export { AvatarEngine, sampleAt, type ClockAppearance } from './clock'
export {
  MIN_BLOCK,
  MAX_BLOCK,
  MAX_BLOCS,
  MAX_CYCLES,
  STEP,
  DEFAULT_BLOCK_DURATION,
  DEFAULT_CYCLE_ID,
  clampDuration,
  makeBlock,
  defaultCycle,
  defaultMontage,
  poseCycle,
  totalDuration,
  offsetOf,
  blockAt,
  blocksWith,
  moveBlock,
  uniqueName,
  nextCycleId,
  parseCycles,
  parseMontage,
  serializeMontage,
  type Block,
  type Cycle,
  type Montage,
} from './cycles'
export { BASE_SCALE, MIN_ZOOM, MAX_ZOOM, clampZoom, mmss, ticksFor } from './timeline'
